name = nodeentity
description = Library for functional node entities.
optional_depends = default, mesecons_mvps, mesecons_luacontroller, digilines, sbz_luacontroller
supported_games = *
author = The4spaceconstants
title = Node entity library
min_minetest_version = 5.14
